package com.example.elsa.domain.member.entity;

public enum Country {
    KOREA, USA, JAPAN, CHINA, FRANCE, GERMANY, ITALY, UK, CANADA, AUSTRALIA,
    NEW_ZEALAND, NETHERLANDS, SWEDEN, NORWAY, DENMARK, FINLAND, SWITZERLAND, AUSTRIA, BELGIUM, SPAIN,
    PORTUGAL, GREECE, TURKEY, POLAND, CZECH_REPUBLIC, SLOVAKIA, HUNGARY, ROMANIA, BULGARIA, CROATIA,
    SERBIA, SLOVENIA, BOSNIA_AND_HERZEGOVINA, MONTENEGRO, MACEDONIA, ALBANIA, KOSOVO, UKRAINE, BELARUS,
    RUSSIA, KAZAKHSTAN, UZBEKISTAN, TURKMENISTAN, TAJIKISTAN, KYRGYZSTAN, GEORGIA, ARMENIA, AZERBAIJAN,
    MOLDOVA, LITHUANIA, LATVIA, ESTONIA, ICELAND, IRELAND, LUXEMBOURG, MALTA, CYPRUS;
}
